import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/header";
import ReduxProvider from "./provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "OpenFire",
    description: "Generated by create next app",
    icons: ['./icon.png'],
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="./icon.png" />
            </head>
            <ReduxProvider>
                <body className={inter.className}>
                    <Header />
                    {children}
                </body>
            </ReduxProvider>
        </html>
    );
}
